FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

WORKDIR /src
COPY . .
RUN dotnet restore "api-server.csproj"
RUN dotnet publish "api-server.csproj" -o /app -c Release

FROM base AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "api-server.dll"]
